import { Pilot, Starship } from '../store/app.model';

export const starshipList: Starship[] = [
  {
    id: '0', // must be 12
    name: 'X-wing',
    model: 'T-65 X-wing',
    manufacturer: 'Incom Corporation',
    cost_in_credits: '149999',
    length: '12.5',
    max_atmosphering_speed: '1050',
    crew: '1',
    passengers: '0',
    cargo_capacity: '110',
    consumables: '1 week',
    hyperdrive_rating: '1.0',
    MGLT: '100',
    starship_class: 'Starfighter',
    pilots: ['https://swapi.dev/api/people/19/'],
    films: ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'],
    created: '2014-12-12T11:19:05.340000Z',
    edited: '2014-12-20T21:23:49.886000Z',
    url: 'https://swapi.dev/api/starships/12/',
  },
];
export const pilotList: Pilot[] = [
  {
    id: '0', // must be 19
    name: 'Jek Tono Porkins',
    height: '180',
    mass: '110',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/26/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: [],
    starships: ['https://swapi.dev/api/starships/12/'],
    created: '2014-12-12T11:16:56.569000Z',
    edited: '2014-12-20T21:17:50.343000Z',
    url: 'https://swapi.dev/api/people/19/',
  },
];
export const starshipListOk: Starship[] = [
  {
    id: '12',
    name: 'X-wing',
    model: 'T-65 X-wing',
    manufacturer: 'Incom Corporation',
    cost_in_credits: '149999',
    length: '12.5',
    max_atmosphering_speed: '1050',
    crew: '1',
    passengers: '0',
    cargo_capacity: '110',
    consumables: '1 week',
    hyperdrive_rating: '1.0',
    MGLT: '100',
    starship_class: 'Starfighter',
    pilots: ['https://swapi.dev/api/people/19/'],
    films: ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'],
    created: '2014-12-12T11:19:05.340000Z',
    edited: '2014-12-20T21:23:49.886000Z',
    url: 'https://swapi.dev/api/starships/12/',
  },
];
export const pilotListOk: Pilot[] = [
  {
    id: '19',
    name: 'Jek Tono Porkins',
    height: '180',
    mass: '110',
    hair_color: 'brown',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: 'unknown',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/planets/26/',
    films: ['https://swapi.dev/api/films/1/'],
    species: [],
    vehicles: [],
    starships: ['https://swapi.dev/api/starships/12/'],
    created: '2014-12-12T11:16:56.569000Z',
    edited: '2014-12-20T21:17:50.343000Z',
    url: 'https://swapi.dev/api/people/19/',
  },
];
